import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';
(()=>{'use strict';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const W=900,H=1800,STORE='vulcet-case-studio-v1';
const canvas=$('#design-canvas'),ctx=canvas.getContext('2d',{alpha:false}),artCanvas=document.createElement('canvas'),textureCanvas=document.createElement('canvas'),textureCtx=textureCanvas.getContext('2d',{alpha:false}),stage=$('.stage'),designStage=$('#design-stage'),status=$('#studio-status');artCanvas.width=textureCanvas.width=W;artCanvas.height=textureCanvas.height=H;
let baseColor='#f1eee7',tool='brush',brushColor='#111111',brushSize=18,brushOpacity=1,textFont='Inter',textWeight=700,layers=[],selected=null,drawing=false,dragging=false,lastPoint=null,history=[],future=[],textureDirty=true,saveTimer=0;
const say=m=>{status.textContent=m};const uid=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const rounded=(c,x,y,w,h,r)=>{c.beginPath();c.roundRect(x,y,w,h,r)};
function cameraPath(c,scale=1){rounded(c,66*scale,69*scale,343*scale,295*scale,54*scale)}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function serial(){return{baseColor,layers:layers.map(l=>{const o={...l};delete o.image;return o})}}
function snapshot(){history.push(JSON.stringify(serial()));if(history.length>45)history.shift();future=[];scheduleSave();updateActions()}
function restore(data,announce=true){baseColor=data.baseColor||'#f1eee7';layers=(data.layers||[]).map(l=>({...l}));selected=null;loadImages().then(()=>{syncControls();render();renderLayers();if(announce)say('Design restored.')})}
function loadImages(){return Promise.all(layers.filter(l=>l.type==='image'&&l.src).map(l=>new Promise(resolve=>{const im=new Image();im.onload=()=>{l.image=im;resolve()};im.onerror=resolve;im.src=l.src})))}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(STORE,JSON.stringify(serial()))}catch(e){say('Design is too large for temporary browser storage. Download it to keep a copy.')}},250)}
function updateActions(){$('[data-action=undo]').disabled=history.length<2;$('[data-action=redo]').disabled=!future.length}
function measureTextLayer(c,l){c.save();c.font=`${l.fontWeight||600} ${l.fontSize||96}px "${l.fontFamily||'Inter'}"`;const lines=(l.text||'Text').split('\n'),spacing=l.letterSpacing||0;l.w=Math.max(40,...lines.map(line=>c.measureText(line).width+Math.max(0,line.length-1)*spacing));l.h=Math.max(l.fontSize||96,lines.length*(l.fontSize||96)*(l.lineHeight||1.05));c.restore()}
function drawSpacedText(c,text,x,y,spacing,align){if(!spacing){c.textAlign=align;c.fillText(text,x,y);return}const widths=[...text].map(ch=>c.measureText(ch).width),total=widths.reduce((a,b)=>a+b,0)+Math.max(0,text.length-1)*spacing;let cursor=align==='left'?x:align==='right'?x-total:x-total/2;c.textAlign='left';[...text].forEach((ch,i)=>{c.fillText(ch,cursor,y);cursor+=widths[i]+spacing})}
function drawLayer(c,l,scale=1){if(l.visible===false)return;c.save();if(l.type==='stroke'){c.globalAlpha=l.opacity;c.globalCompositeOperation=l.erase?'destination-out':'source-over';c.strokeStyle=l.color;c.lineWidth=l.size*scale;c.lineCap='round';c.lineJoin='round';c.beginPath();l.points.forEach((p,i)=>{const x=p.x*scale,y=p.y*scale;i?c.lineTo(x,y):c.moveTo(x,y)});if(l.points.length===1)c.lineTo((l.points[0].x+.1)*scale,l.points[0].y*scale);c.stroke()}else if(l.type==='image'&&l.image){c.translate(l.x*scale,l.y*scale);c.rotate(l.rotation);c.globalAlpha=l.opacity??1;const w=l.w*l.scale*scale,h=l.h*l.scale*scale;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(l.image,-w/2,-h/2,w,h)}else if(l.type==='text'){measureTextLayer(c,l);c.translate(l.x*scale,l.y*scale);c.rotate(l.rotation);c.scale(l.scale*scale,l.scale*scale);c.globalAlpha=l.opacity??1;c.fillStyle=l.color||'#111';c.font=`${l.fontWeight||600} ${l.fontSize||96}px "${l.fontFamily||'Inter'}"`;c.textBaseline='middle';const lines=(l.text||'Text').split('\n'),lineH=(l.fontSize||96)*(l.lineHeight||1.05),start=-(lines.length-1)*lineH/2;lines.forEach((line,i)=>drawSpacedText(c,line,0,start+i*lineH,(l.letterSpacing||0),l.align||'center'))}c.restore()}
function renderArtwork(target,scale){const aw=W*scale,ah=H*scale;if(artCanvas.width!==aw||artCanvas.height!==ah){artCanvas.width=aw;artCanvas.height=ah}const a=artCanvas.getContext('2d');a.clearRect(0,0,aw,ah);layers.forEach(l=>drawLayer(a,l,scale));target.save();target.globalCompositeOperation='source-over';target.globalAlpha=1;target.fillStyle=baseColor;target.fillRect(0,0,aw,ah);target.drawImage(artCanvas,0,0);target.restore()}
function renderTexture(){if(textureCanvas.width!==W||textureCanvas.height!==H){textureCanvas.width=W;textureCanvas.height=H}renderArtwork(textureCtx,1);textureDirty=true;updateTexture()}
function render(target=ctx,scale=1){renderArtwork(target,scale);if(target===ctx){drawSelection();renderTexture();designStage.style.background=baseColor}}
function drawSelection(){const l=layers.find(x=>x.id===selected);if(!l||!['image','text'].includes(l.type)||l.visible===false)return;if(l.type==='text')measureTextLayer(ctx,l);ctx.save();ctx.translate(l.x,l.y);ctx.rotate(l.rotation);const w=l.w*l.scale,h=l.h*l.scale;ctx.strokeStyle='#285cff';ctx.lineWidth=4;ctx.setLineDash([14,9]);ctx.strokeRect(-w/2,-h/2,w,h);ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.strokeStyle='#285cff';for(const [x,y] of [[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]]){ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
function hitObject(p,l){if(!['image','text'].includes(l.type)||l.visible===false)return false;if(l.type==='text')measureTextLayer(ctx,l);const dx=p.x-l.x,dy=p.y-l.y,co=Math.cos(-l.rotation),si=Math.sin(-l.rotation),x=dx*co-dy*si,y=dx*si+dy*co;return Math.abs(x)<=l.w*l.scale/2&&Math.abs(y)<=l.h*l.scale/2}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);const p=point(e);const hit=[...layers].reverse().find(l=>hitObject(p,l));if(hit){selected=hit.id;dragging=true;lastPoint=p;render();renderLayers();return}selected=null;drawing=true;const l={id:uid(),type:'stroke',name:tool==='eraser'?'Eraser':'Brush stroke',color:brushColor,size:brushSize,opacity:brushOpacity,erase:tool==='eraser',visible:true,points:[p]};layers.push(l);selected=l.id;lastPoint=p;render();renderLayers()});
canvas.addEventListener('pointermove',e=>{if(!drawing&&!dragging)return;const p=point(e);if(drawing){layers[layers.length-1].points.push(p)}else{const l=layers.find(x=>x.id===selected);l.x+=p.x-lastPoint.x;l.y+=p.y-lastPoint.y;lastPoint=p}render()});
const pointerEnd=()=>{if(drawing||dragging){drawing=dragging=false;lastPoint=null;snapshot();renderLayers()}};canvas.addEventListener('pointerup',pointerEnd);canvas.addEventListener('pointercancel',pointerEnd);
function renderLayers(){const list=$('#layers-list');list.innerHTML='';[...layers].reverse().forEach((l,i)=>{const li=document.createElement('li');li.className=`layer-item${l.id===selected?' is-selected':''}${l.visible===false?' is-hidden':''}`;li.dataset.id=l.id;li.tabIndex=0;const type=l.type==='image'?'IMG':l.type==='text'?'TXT':l.erase?'ER':'BR';li.innerHTML=`<span class="layer-thumb">${type}</span><span class="layer-copy"><strong>${escapeHtml(l.name||'Layer')}</strong><small>${l.type} · ${layers.length-i}</small></span><span class="layer-buttons"><button class="layer-visibility" type="button" aria-label="${l.visible===false?'Show layer':'Hide layer'}">${l.visible===false?'○':'●'}</button><button class="layer-delete" type="button" aria-label="Delete layer">×</button></span>`;const choose=()=>{selected=l.id;render();renderLayers()};li.onclick=choose;li.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();choose()}};$('.layer-visibility',li).onclick=e=>{e.stopPropagation();l.visible=l.visible===false;selected=l.id;snapshot();render();renderLayers();say(l.visible===false?'Layer hidden.':'Layer visible.')};$('.layer-delete',li).onclick=e=>{e.stopPropagation();selected=l.id;mutate('delete');say('Layer deleted.')};list.append(li)});$('#layer-count').textContent=layers.length;renderSelectionControls()}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function commonSelection(l,label){return `<div class="selection-title"><strong>${escapeHtml(l.name||'Layer')}</strong><span>${label}</span></div><label>Scale <input data-property="scale" type="range" min="0.1" max="4" step="0.01" value="${l.scale||1}"></label><label>Rotation <input data-property="rotation" type="range" min="-180" max="180" step="1" value="${Math.round((l.rotation||0)*180/Math.PI)}"></label><label>${l.type==='image'?'Image strength':'Opacity'} <input data-property="opacity" type="range" min="0.2" max="1" step="0.01" value="${l.opacity??1}"></label>`}
function bindSelection(l,box){$$('[data-property]',box).forEach(input=>{input.oninput=()=>{const p=input.dataset.property;if(p==='rotation')l.rotation=+input.value*Math.PI/180;else if(p==='text'||p==='color'||p==='fontFamily'||p==='align')l[p]=input.value;else l[p]=+input.value;if(p==='text')l.name=(input.value.split('\n')[0]||'Text').slice(0,28);render()};input.onchange=()=>{snapshot();renderLayers()}});$$('[data-align]',box).forEach(b=>b.onclick=()=>{l.align=b.dataset.align;snapshot();render();renderLayers()})}
function renderSelectionControls(){const box=$('#selection-controls'),l=layers.find(x=>x.id===selected);if(!l){box.innerHTML='<p>Select a layer to transform, reorder, hide or delete it.</p>';return}if(l.type==='image'){box.innerHTML=commonSelection(l,'Image');bindSelection(l,box)}else if(l.type==='text'){box.innerHTML=`${commonSelection(l,'Text')}<label>Content <textarea data-property="text" rows="2" maxlength="120">${escapeHtml(l.text)}</textarea></label><div class="selection-grid"><label>Typeface <select data-property="fontFamily"><option value="Inter"${l.fontFamily==='Inter'?' selected':''}>Sans</option><option value="Instrument Serif"${l.fontFamily==='Instrument Serif'?' selected':''}>Serif</option><option value="Arial Black"${l.fontFamily==='Arial Black'?' selected':''}>Display</option><option value="monospace"${l.fontFamily==='monospace'?' selected':''}>Mono</option></select></label><label>Size <input data-property="fontSize" type="number" min="24" max="280" value="${l.fontSize}"></label><label>Tracking <input data-property="letterSpacing" type="number" min="-8" max="40" value="${l.letterSpacing||0}"></label><label>Line height <input data-property="lineHeight" type="number" min="0.8" max="2" step="0.05" value="${l.lineHeight||1.05}"></label></div><label>Colour <input data-property="color" type="color" value="${l.color||'#111111'}"></label><div class="text-align" role="group" aria-label="Text alignment"><button type="button" data-align="left" class="${l.align==='left'?'is-active':''}">Left</button><button type="button" data-align="center" class="${!l.align||l.align==='center'?'is-active':''}">Centre</button><button type="button" data-align="right" class="${l.align==='right'?'is-active':''}">Right</button></div>`;bindSelection(l,box)}else box.innerHTML=`<div class="selection-title"><strong>${l.erase?'Eraser':'Brush stroke'}</strong><span>Drawing</span></div><p>${l.points.length} points · use the layer controls to reorder, duplicate or delete.</p>`}
function setTool(next){tool=next;$$('[data-tool]').forEach(b=>{const on=b.dataset.tool===next;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',on)});say(`${next==='brush'?'Brush':'Eraser'} selected.`)}
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
$$('.swatch').forEach(b=>b.onclick=()=>setBase(b.dataset.color,b));$('#case-color').oninput=e=>setBase(e.target.value);function setBase(color,button){baseColor=color;$$('.swatch').forEach(b=>b.classList.toggle('is-active',b===button));render();snapshot()}
$('#brush-color').oninput=e=>brushColor=e.target.value;$('#brush-size').oninput=e=>{brushSize=+e.target.value;$('#size-value').value=brushSize};$('#brush-opacity').oninput=e=>{brushOpacity=+e.target.value/100;$('#opacity-value').value=`${e.target.value}%`};
$$('.font-preset').forEach(b=>b.onclick=()=>{textFont=b.dataset.font;textWeight=+b.dataset.weight;$$('.font-preset').forEach(x=>x.classList.toggle('is-active',x===b))});$('#add-text').onclick=()=>{const text=$('#text-input').value.trim()||'VULCET',fontSize=Math.max(24,Math.min(280,+$('#text-size').value||96));const l={id:uid(),type:'text',name:text.split('\n')[0].slice(0,28),text,fontFamily:textFont,fontWeight:textWeight,fontSize,letterSpacing:0,lineHeight:1.05,align:'center',color:$('#text-color').value,opacity:1,visible:true,x:W/2,y:H/2,scale:1,rotation:0,w:300,h:fontSize};layers.push(l);selected=l.id;snapshot();render();renderLayers();say('Text layer added. Drag it on the case or refine it in Layers.')};
$('#show-safe').onchange=e=>$('.safe-guide').hidden=!e.target.checked;$('#show-bleed').onchange=e=>$('.bleed-guide').hidden=!e.target.checked;
$('#image-upload').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)){say('Choose a PNG, JPG or WebP image.');return}const reader=new FileReader();reader.onload=()=>{const im=new Image();im.onload=()=>{const ratio=Math.min(640/im.width,900/im.height,4);const l={id:uid(),type:'image',name:f.name.slice(0,28),src:reader.result,image:im,x:W/2,y:H/2,w:im.width*ratio,h:im.height*ratio,scale:1,rotation:0,opacity:1,visible:true};layers.push(l);selected=l.id;snapshot();render();renderLayers();say('Image added at high visibility. Drag it on the case or refine it in Layers.')};im.src=reader.result};reader.readAsDataURL(f);e.target.value=''};
function mutate(action){const i=layers.findIndex(l=>l.id===selected);if(i<0)return false;const l=layers[i];if(action==='delete')layers.splice(i,1);if(action==='duplicate'){const copy={...l,id:uid(),name:`${l.name} copy`,x:(l.x||W/2)+34,y:(l.y||H/2)+34,points:l.points?l.points.map(p=>({...p})):undefined};layers.splice(i+1,0,copy);selected=copy.id}if(action==='forward'&&i<layers.length-1){layers.splice(i,1);layers.splice(i+1,0,l)}if(action==='backward'&&i>0){layers.splice(i,1);layers.splice(i-1,0,l)}snapshot();render();renderLayers();return true}
function undo(){if(history.length<2)return;future.push(history.pop());restore(JSON.parse(history[history.length-1]),false);updateActions();say('Undone.')}function redo(){if(!future.length)return;const s=future.pop();history.push(s);restore(JSON.parse(s),false);updateActions();say('Redone.')}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='undo')undo();else if(a==='redo')redo();else if(['forward','backward','duplicate','delete'].includes(a)){if(!mutate(a))say('Select a layer first.')}else if(a==='clear'){if(layers.length){layers=[];selected=null;snapshot();render();renderLayers();say('Artwork cleared.')}}else if(a==='reset')reset();else if(a==='download')download()}));
function reset(){baseColor='#f1eee7';layers=[];selected=null;$('#show-safe').checked=true;$('#show-bleed').checked=true;$('.safe-guide').hidden=false;$('.bleed-guide').hidden=false;snapshot();syncControls();render();renderLayers();say('Studio reset.')}
function syncControls(){$('#case-color').value=baseColor;$$('.swatch').forEach(b=>b.classList.toggle('is-active',b.dataset.color.toLowerCase()===baseColor.toLowerCase()))}
function download(){const out=document.createElement('canvas');out.width=1800;out.height=3600;const c=out.getContext('2d');render(c,2);c.save();c.globalCompositeOperation='destination-out';cameraPath(c,2);c.fill();c.restore();out.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vulcet-case-studio.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);say('High-resolution PNG downloaded.')},'image/png')}
document.addEventListener('keydown',e=>{const tag=e.target.tagName;if(/INPUT|TEXTAREA|SELECT/.test(tag))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.key==='Delete'||e.key==='Backspace')&&selected){e.preventDefault();mutate('delete')}else if(e.key==='Escape'){selected=null;render();renderLayers()}});
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));function setMode(mode){stage.dataset.view=mode;$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',on)});$('[data-design-hint]').hidden=mode!=='design';$('[data-preview-hint]').hidden=mode!=='preview';$('[data-view-controls]').hidden=mode!=='preview';if(mode==='preview'){resize3D();updateTexture(true)}say(mode==='preview'?'3D preview active. Drag to rotate.':'Design view active.')}
$$('[data-open-panel]').forEach(b=>b.onclick=()=>{$(`#${b.dataset.openPanel}`).classList.add('is-open')});$$('[data-close-panel]').forEach(b=>b.onclick=()=>b.closest('aside').classList.remove('is-open'));document.addEventListener('pointerdown',e=>{if(innerWidth>820)return;$$('aside.is-open').forEach(p=>{if(!p.contains(e.target)&&!e.target.closest('[data-open-panel]'))p.classList.remove('is-open')})});

let renderer,scene,camera,phone,caseTexture,raf,viewTarget={x:.18,y:Math.PI-.5,z:0},distance=7.2,pointer3D=null;
function init3D(){const host=$('#preview-stage');try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,0,distance);scene.add(new THREE.HemisphereLight(0xffffff,0x313139,2.7));const key=new THREE.DirectionalLight(0xffffff,4.5);key.position.set(4,5,6);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0xd8e5ff,2.4);rim.position.set(-4,1,-3);scene.add(rim);const fill=new THREE.DirectionalLight(0xffeee1,1.3);fill.position.set(1,-4,3);scene.add(fill);phone=new THREE.Group();scene.add(phone);buildPhone();renderer.domElement.addEventListener('pointerdown',e=>{renderer.domElement.setPointerCapture(e.pointerId);pointer3D={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointermove',e=>{if(!pointer3D)return;viewTarget.y+=(e.clientX-pointer3D.x)*.009;viewTarget.x=Math.max(-1.2,Math.min(1.2,viewTarget.x+(e.clientY-pointer3D.y)*.009));pointer3D={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',()=>pointer3D=null);renderer.domElement.addEventListener('pointercancel',()=>pointer3D=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(5,Math.min(9,distance+e.deltaY*.004))},{passive:false});let pinch=0;renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)distance=Math.max(5,Math.min(9,distance+(pinch-d)*.012));pinch=d}},{passive:false});renderer.domElement.addEventListener('touchend',()=>pinch=0);resize3D();animate()}catch(e){$('.webgl-message').hidden=false;say('3D preview is unavailable in this browser.')}}
function rrShape(w,h,r,cx=0,cy=0){const s=new THREE.Shape(),x=cx-w/2,y=cy-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function buildPhone(){
 const titanium=new THREE.MeshPhysicalMaterial({color:0x77736e,roughness:.28,metalness:.92,clearcoat:.28}),darkGlass=new THREE.MeshPhysicalMaterial({color:0x030407,roughness:.08,metalness:.18,clearcoat:1,clearcoatRoughness:.05});
 const bodyGeo=new THREE.ExtrudeGeometry(rrShape(2.04,4.12,.255),{depth:.2,bevelEnabled:true,bevelSegments:5,steps:1,bevelSize:.052,bevelThickness:.05});bodyGeo.center();const body=new THREE.Mesh(bodyGeo,titanium);body.castShadow=true;phone.add(body);
 const screen=new THREE.Mesh(new THREE.ShapeGeometry(rrShape(1.91,3.98,.215)),darkGlass);screen.position.z=.205;phone.add(screen);
 const islandFront=new THREE.Mesh(new THREE.ShapeGeometry(rrShape(.5,.14,.07,0,1.55)),new THREE.MeshBasicMaterial({color:0x000000}));islandFront.position.z=.212;phone.add(islandFront);
 const buttonMat=new THREE.MeshStandardMaterial({color:0x696662,roughness:.24,metalness:.95});[[-1.075,.86,.06,.36],[-1.075,.27,.06,.62],[1.075,.48,.06,.78],[-1.075,1.35,.06,.22]].forEach(([x,y,w,h])=>{const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,.11),buttonMat);b.position.set(x,y,.01);b.castShadow=true;phone.add(b)});
 const caseShape=rrShape(2.18,4.26,.3),hole=rrShape(.83,.79,.18,-.5,1.39);caseShape.holes.push(hole);const geo=new THREE.ShapeGeometry(caseShape,28),pos=geo.attributes.position,uv=geo.attributes.uv;for(let i=0;i<pos.count;i++)uv.setXY(i,(pos.getX(i)+1.09)/2.18,(pos.getY(i)+2.13)/4.26);
 caseTexture=new THREE.CanvasTexture(textureCanvas);caseTexture.colorSpace=THREE.SRGBColorSpace;caseTexture.anisotropy=Math.min(12,renderer.capabilities.getMaxAnisotropy());const backMat=new THREE.MeshPhysicalMaterial({map:caseTexture,emissive:0xffffff,emissiveMap:caseTexture,emissiveIntensity:.16,roughness:.36,metalness:0,clearcoat:.5,clearcoatRoughness:.28,side:THREE.DoubleSide});const back=new THREE.Mesh(geo,backMat);back.position.z=-.19;back.rotation.y=Math.PI;back.castShadow=true;phone.add(back);
 const rimShape=rrShape(2.18,4.26,.3);rimShape.holes.push(rrShape(1.99,4.07,.235));const rimGeo=new THREE.ExtrudeGeometry(rimShape,{depth:.27,bevelEnabled:true,bevelSegments:4,steps:1,bevelSize:.052,bevelThickness:.045});rimGeo.center();const rimMesh=new THREE.Mesh(rimGeo,new THREE.MeshPhysicalMaterial({color:new THREE.Color(baseColor),roughness:.34,clearcoat:.72,clearcoatRoughness:.22}));rimMesh.name='case-rim';rimMesh.position.z=-.075;rimMesh.castShadow=true;phone.add(rimMesh);
 const islandGeo=new THREE.ExtrudeGeometry(rrShape(.83,.79,.18),{depth:.075,bevelEnabled:true,bevelSize:.026,bevelThickness:.025,bevelSegments:4});islandGeo.center();const cameraIsland=new THREE.Mesh(islandGeo,new THREE.MeshPhysicalMaterial({color:0x343434,roughness:.24,metalness:.78,clearcoat:.45}));cameraIsland.position.set(.5,1.39,-.285);cameraIsland.rotation.y=Math.PI;phone.add(cameraIsland);
 const lensPositions=[[.68,1.57],[.31,1.47],[.59,1.19]];lensPositions.forEach(([x,y])=>{const ring=new THREE.Mesh(new THREE.CylinderGeometry(.165,.175,.075,40),titanium);ring.rotation.x=Math.PI/2;ring.position.set(x,y,-.35);phone.add(ring);const lens=new THREE.Mesh(new THREE.CylinderGeometry(.128,.138,.087,40),new THREE.MeshPhysicalMaterial({color:0x030711,roughness:.04,metalness:.5,clearcoat:1,iridescence:.45,iridescenceIOR:1.45}));lens.rotation.x=Math.PI/2;lens.position.set(x,y,-.395);phone.add(lens)});
 const flash=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,.025,32),new THREE.MeshPhysicalMaterial({color:0xfff4d1,emissive:0xffe7a5,emissiveIntensity:.25,roughness:.2}));flash.rotation.x=Math.PI/2;flash.position.set(.31,1.19,-.348);phone.add(flash);const lidar=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,.025,24),darkGlass);lidar.rotation.x=Math.PI/2;lidar.position.set(.34,1.68,-.348);phone.add(lidar);
 phone.rotation.set(viewTarget.x,viewTarget.y,0)
}
function updateTexture(force=false){if(!renderer||(!textureDirty&&!force))return;caseTexture.needsUpdate=true;const rim=phone.getObjectByName('case-rim');if(rim)rim.material.color.set(baseColor);textureDirty=false}
function resize3D(){if(!renderer)return;const h=$('#preview-stage'),w=h.clientWidth||600,hh=h.clientHeight||600;renderer.setSize(w,hh,false);camera.aspect=w/hh;camera.updateProjectionMatrix()}
function animate(){raf=requestAnimationFrame(animate);if(!renderer)return;phone.rotation.x+=(viewTarget.x-phone.rotation.x)*.09;phone.rotation.y+=(viewTarget.y-phone.rotation.y)*.09;camera.position.z+=(distance-camera.position.z)*.1;renderer.render(scene,camera)}
$$('[data-view-controls] [data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='front'){viewTarget={x:0,y:0,z:0};distance=7.2}else if(v==='back'){viewTarget={x:0,y:Math.PI,z:0};distance=7.2}else if(v==='angle'){viewTarget={x:.2,y:Math.PI-.55,z:0};distance=7.2}else{viewTarget={x:.18,y:Math.PI-.5,z:0};distance=7.2}});addEventListener('resize',resize3D);
try{const saved=localStorage.getItem(STORE);if(saved)restore(JSON.parse(saved),false);else{snapshot();render();renderLayers()}}catch(e){snapshot();render();renderLayers()}updateActions();init3D();
})();
