import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';
(()=>{'use strict';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const W=900,H=1800,STORE='vulcet-case-studio-v1';
const canvas=$('#design-canvas'),ctx=canvas.getContext('2d',{alpha:false}),artCanvas=document.createElement('canvas'),textureCanvas=document.createElement('canvas'),textureCtx=textureCanvas.getContext('2d',{alpha:false}),stage=$('.stage'),designStage=$('#design-stage'),status=$('#studio-status');artCanvas.width=textureCanvas.width=W;artCanvas.height=textureCanvas.height=H;
let baseColor='#f1eee7',tool='brush',brushColor='#111111',brushSize=18,brushOpacity=1,layers=[],selected=null,drawing=false,dragging=false,lastPoint=null,history=[],future=[],textureDirty=true,saveTimer=0;
const say=m=>{status.textContent=m};const uid=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const rounded=(c,x,y,w,h,r)=>{c.beginPath();c.roundRect(x,y,w,h,r)};
function cameraPath(c,scale=1){rounded(c,66*scale,69*scale,343*scale,295*scale,54*scale)}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function serial(){return{baseColor,layers:layers.map(l=>{const o={...l};delete o.image;return o})}}
function snapshot(){history.push(JSON.stringify(serial()));if(history.length>45)history.shift();future=[];scheduleSave();updateActions()}
function restore(data,announce=true){baseColor=data.baseColor||'#f1eee7';layers=(data.layers||[]).map(l=>({...l}));selected=null;loadImages().then(()=>{syncControls();render();renderLayers();if(announce)say('Design restored.')})}
function loadImages(){return Promise.all(layers.filter(l=>l.type==='image'&&l.src).map(l=>new Promise(resolve=>{const im=new Image();im.onload=()=>{l.image=im;resolve()};im.onerror=resolve;im.src=l.src})))}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(STORE,JSON.stringify(serial()))}catch(e){say('Design is too large for temporary browser storage. Download it to keep a copy.')}},250)}
function updateActions(){$('[data-action=undo]').disabled=history.length<2;$('[data-action=redo]').disabled=!future.length}
function drawLayer(c,l,scale=1){c.save();if(l.type==='stroke'){c.globalAlpha=l.opacity;c.globalCompositeOperation=l.erase?'destination-out':'source-over';c.strokeStyle=l.color;c.lineWidth=l.size*scale;c.lineCap='round';c.lineJoin='round';c.beginPath();l.points.forEach((p,i)=>{const x=p.x*scale,y=p.y*scale;i?c.lineTo(x,y):c.moveTo(x,y)});if(l.points.length===1)c.lineTo((l.points[0].x+.1)*scale,l.points[0].y*scale);c.stroke()}else if(l.type==='image'&&l.image){c.translate(l.x*scale,l.y*scale);c.rotate(l.rotation);c.globalAlpha=l.opacity??1;const w=l.w*l.scale*scale,h=l.h*l.scale*scale;c.drawImage(l.image,-w/2,-h/2,w,h)}c.restore()}
function renderArtwork(target,scale){const aw=W*scale,ah=H*scale;if(artCanvas.width!==aw||artCanvas.height!==ah){artCanvas.width=aw;artCanvas.height=ah}const a=artCanvas.getContext('2d');a.clearRect(0,0,aw,ah);layers.forEach(l=>drawLayer(a,l,scale));target.save();target.globalCompositeOperation='source-over';target.globalAlpha=1;target.fillStyle=baseColor;target.fillRect(0,0,aw,ah);target.drawImage(artCanvas,0,0);target.restore()}
function renderTexture(){if(textureCanvas.width!==W||textureCanvas.height!==H){textureCanvas.width=W;textureCanvas.height=H}renderArtwork(textureCtx,1);textureDirty=true;updateTexture()}
function render(target=ctx,scale=1){renderArtwork(target,scale);if(target===ctx){drawSelection();renderTexture();designStage.style.background=baseColor}}
function drawSelection(){const l=layers.find(x=>x.id===selected);if(!l||l.type!=='image')return;ctx.save();ctx.translate(l.x,l.y);ctx.rotate(l.rotation);const w=l.w*l.scale,h=l.h*l.scale;ctx.strokeStyle='#2d5bff';ctx.lineWidth=5;ctx.setLineDash([16,10]);ctx.strokeRect(-w/2,-h/2,w,h);ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.strokeStyle='#2d5bff';for(const [x,y] of [[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]]){ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
function hitImage(p,l){const dx=p.x-l.x,dy=p.y-l.y,co=Math.cos(-l.rotation),si=Math.sin(-l.rotation),x=dx*co-dy*si,y=dx*si+dy*co;return Math.abs(x)<=l.w*l.scale/2&&Math.abs(y)<=l.h*l.scale/2}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);const p=point(e);const hit=[...layers].reverse().find(l=>l.type==='image'&&hitImage(p,l));if(hit){selected=hit.id;dragging=true;lastPoint=p;render();renderLayers();return}selected=null;drawing=true;const l={id:uid(),type:'stroke',name:tool==='eraser'?'Eraser':'Brush stroke',color:brushColor,size:brushSize,opacity:brushOpacity,erase:tool==='eraser',points:[p]};layers.push(l);selected=l.id;lastPoint=p;render();renderLayers()});
canvas.addEventListener('pointermove',e=>{if(!drawing&&!dragging)return;const p=point(e);if(drawing){layers[layers.length-1].points.push(p)}else{const l=layers.find(x=>x.id===selected);l.x+=p.x-lastPoint.x;l.y+=p.y-lastPoint.y;lastPoint=p}render()});
const pointerEnd=()=>{if(drawing||dragging){drawing=dragging=false;lastPoint=null;snapshot();renderLayers()}};canvas.addEventListener('pointerup',pointerEnd);canvas.addEventListener('pointercancel',pointerEnd);
function renderLayers(){const list=$('#layers-list');list.innerHTML='';[...layers].reverse().forEach((l,i)=>{const li=document.createElement('li');li.className=`layer-item${l.id===selected?' is-selected':''}`;li.dataset.id=l.id;li.tabIndex=0;li.innerHTML=`<span class="layer-thumb">${l.type==='image'?'IMG':l.erase?'ER':'BR'}</span><strong>${escapeHtml(l.name||'Layer')}</strong><small>${layers.length-i}</small>`;const choose=()=>{selected=l.id;render();renderLayers()};li.onclick=choose;li.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}};list.append(li)});$('#layer-count').textContent=layers.length;renderSelectionControls()}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function renderSelectionControls(){const box=$('#selection-controls'),l=layers.find(x=>x.id===selected);if(!l){box.innerHTML='<p>Select an image or drawing layer to edit it.</p>';return}if(l.type==='image'){box.innerHTML=`<label>Scale <input data-property="scale" type="range" min="0.1" max="3" step="0.01" value="${l.scale}"></label><label>Rotation <input data-property="rotation" type="range" min="-180" max="180" step="1" value="${Math.round(l.rotation*180/Math.PI)}"></label><label>Opacity <input data-property="opacity" type="range" min="0.05" max="1" step="0.01" value="${l.opacity??1}"></label>`;$$('input',box).forEach(input=>{input.oninput=()=>{if(input.dataset.property==='rotation')l.rotation=+input.value*Math.PI/180;else l[input.dataset.property]=+input.value;render()};input.onchange=()=>snapshot()})}else box.innerHTML=`<p>${l.erase?'Eraser':'Brush'} layer · ${l.points.length} points</p>`}
function setTool(next){tool=next;$$('[data-tool]').forEach(b=>{const on=b.dataset.tool===next;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',on)});say(`${next==='brush'?'Brush':'Eraser'} selected.`)}
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
$$('.swatch').forEach(b=>b.onclick=()=>setBase(b.dataset.color,b));$('#case-color').oninput=e=>setBase(e.target.value);function setBase(color,button){baseColor=color;$$('.swatch').forEach(b=>b.classList.toggle('is-active',b===button));render();snapshot()}
$('#brush-color').oninput=e=>brushColor=e.target.value;$('#brush-size').oninput=e=>{brushSize=+e.target.value;$('#size-value').value=brushSize};$('#brush-opacity').oninput=e=>{brushOpacity=+e.target.value/100;$('#opacity-value').value=`${e.target.value}%`};
$('#show-safe').onchange=e=>$('.safe-guide').hidden=!e.target.checked;$('#show-bleed').onchange=e=>$('.bleed-guide').hidden=!e.target.checked;
$('#image-upload').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)){say('Choose a PNG, JPG or WebP image.');return}const reader=new FileReader();reader.onload=()=>{const im=new Image();im.onload=()=>{const max=520,ratio=Math.min(max/im.width,max/im.height,1);const l={id:uid(),type:'image',name:f.name.slice(0,28),src:reader.result,image:im,x:W/2,y:H/2,w:im.width*ratio,h:im.height*ratio,scale:1,rotation:0,opacity:1};layers.push(l);selected=l.id;snapshot();render();renderLayers();say('Image added. Drag it on the case or use the selection controls.')};im.src=reader.result};reader.readAsDataURL(f);e.target.value=''};
function mutate(action){const i=layers.findIndex(l=>l.id===selected);if(i<0)return false;const l=layers[i];if(action==='delete')layers.splice(i,1);if(action==='duplicate'){const copy={...l,id:uid(),name:`${l.name} copy`,x:(l.x||W/2)+34,y:(l.y||H/2)+34,points:l.points?l.points.map(p=>({...p})):undefined};layers.splice(i+1,0,copy);selected=copy.id}if(action==='forward'&&i<layers.length-1){layers.splice(i,1);layers.splice(i+1,0,l)}if(action==='backward'&&i>0){layers.splice(i,1);layers.splice(i-1,0,l)}snapshot();render();renderLayers();return true}
function undo(){if(history.length<2)return;future.push(history.pop());restore(JSON.parse(history[history.length-1]),false);updateActions();say('Undone.')}function redo(){if(!future.length)return;const s=future.pop();history.push(s);restore(JSON.parse(s),false);updateActions();say('Redone.')}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='undo')undo();else if(a==='redo')redo();else if(['forward','backward','duplicate','delete'].includes(a)){if(!mutate(a))say('Select a layer first.')}else if(a==='clear'){if(layers.length){layers=[];selected=null;snapshot();render();renderLayers();say('Artwork cleared.')}}else if(a==='reset')reset();else if(a==='download')download()}));
function reset(){baseColor='#f1eee7';layers=[];selected=null;$('#show-safe').checked=true;$('#show-bleed').checked=true;$('.safe-guide').hidden=false;$('.bleed-guide').hidden=false;snapshot();syncControls();render();renderLayers();say('Studio reset.')}
function syncControls(){$('#case-color').value=baseColor;$$('.swatch').forEach(b=>b.classList.toggle('is-active',b.dataset.color.toLowerCase()===baseColor.toLowerCase()))}
function download(){const out=document.createElement('canvas');out.width=1800;out.height=3600;const c=out.getContext('2d');render(c,2);c.save();c.globalCompositeOperation='destination-out';cameraPath(c,2);c.fill();c.restore();out.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vulcet-case-studio.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);say('High-resolution PNG downloaded.')},'image/png')}
document.addEventListener('keydown',e=>{const tag=e.target.tagName;if(/INPUT|TEXTAREA|SELECT/.test(tag))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.key==='Delete'||e.key==='Backspace')&&selected){e.preventDefault();mutate('delete')}else if(e.key==='Escape'){selected=null;render();renderLayers()}});
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));function setMode(mode){stage.dataset.view=mode;$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',on)});$('[data-design-hint]').hidden=mode!=='design';$('[data-preview-hint]').hidden=mode!=='preview';$('[data-view-controls]').hidden=mode!=='preview';if(mode==='preview'){resize3D();updateTexture(true)}say(mode==='preview'?'3D preview active. Drag to rotate.':'Design view active.')}
$$('[data-open-panel]').forEach(b=>b.onclick=()=>{$(`#${b.dataset.openPanel}`).classList.add('is-open')});$$('[data-close-panel]').forEach(b=>b.onclick=()=>b.closest('aside').classList.remove('is-open'));document.addEventListener('pointerdown',e=>{if(innerWidth>820)return;$$('aside.is-open').forEach(p=>{if(!p.contains(e.target)&&!e.target.closest('[data-open-panel]'))p.classList.remove('is-open')})});

let renderer,scene,camera,phone,caseTexture,raf,viewTarget={x:.18,y:Math.PI-.5,z:0},distance=7.2,pointer3D=null;
function init3D(){const host=$('#preview-stage');try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,0,distance);scene.add(new THREE.HemisphereLight(0xffffff,0x44444c,2.2));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(4,5,6);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0xd8e5ff,2);rim.position.set(-4,1,-3);scene.add(rim);phone=new THREE.Group();scene.add(phone);buildPhone();renderer.domElement.addEventListener('pointerdown',e=>{renderer.domElement.setPointerCapture(e.pointerId);pointer3D={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointermove',e=>{if(!pointer3D)return;viewTarget.y+=(e.clientX-pointer3D.x)*.009;viewTarget.x=Math.max(-1.2,Math.min(1.2,viewTarget.x+(e.clientY-pointer3D.y)*.009));pointer3D={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',()=>pointer3D=null);renderer.domElement.addEventListener('pointercancel',()=>pointer3D=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(5,Math.min(9,distance+e.deltaY*.004))},{passive:false});let pinch=0;renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch)distance=Math.max(5,Math.min(9,distance+(pinch-d)*.012));pinch=d}},{passive:false});renderer.domElement.addEventListener('touchend',()=>pinch=0);resize3D();animate()}catch(e){$('.webgl-message').hidden=false;say('3D preview is unavailable in this browser.')}}
function rrShape(w,h,r,cx=0,cy=0){const s=new THREE.Shape(),x=cx-w/2,y=cy-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function buildPhone(){const bodyShape=rrShape(2.04,4.12,.25),bodyGeo=new THREE.ExtrudeGeometry(bodyShape,{depth:.18,bevelEnabled:true,bevelSegments:4,steps:1,bevelSize:.055,bevelThickness:.045});bodyGeo.center();const body=new THREE.Mesh(bodyGeo,new THREE.MeshStandardMaterial({color:0x171719,roughness:.32,metalness:.72}));body.castShadow=true;phone.add(body);const screenShape=rrShape(1.88,3.94,.2),screenGeo=new THREE.ShapeGeometry(screenShape),screen=new THREE.Mesh(screenGeo,new THREE.MeshPhysicalMaterial({color:0x08090c,roughness:.12,metalness:.25,clearcoat:1}));screen.position.z=.185;screen.rotation.z=Math.PI;phone.add(screen);
 const caseShape=rrShape(2.18,4.26,.3),hole=rrShape(.79,.75,.17,-.5,1.39);caseShape.holes.push(hole);const geo=new THREE.ShapeGeometry(caseShape,24);const pos=geo.attributes.position;const uv=geo.attributes.uv;for(let i=0;i<pos.count;i++){uv.setXY(i,(pos.getX(i)+1.09)/2.18,(pos.getY(i)+2.13)/4.26)}caseTexture=new THREE.CanvasTexture(textureCanvas);caseTexture.colorSpace=THREE.SRGBColorSpace;caseTexture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());const back=new THREE.Mesh(geo,new THREE.MeshPhysicalMaterial({map:caseTexture,roughness:.48,metalness:.02,clearcoat:.45,clearcoatRoughness:.35,side:THREE.DoubleSide}));back.position.z=-.18;back.rotation.y=Math.PI;back.castShadow=true;phone.add(back);const rimGeo=new THREE.ExtrudeGeometry(caseShape,{depth:.24,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.055,bevelThickness:.04});rimGeo.center();const rimMesh=new THREE.Mesh(rimGeo,new THREE.MeshPhysicalMaterial({color:new THREE.Color(baseColor),roughness:.4,clearcoat:.5,transparent:true,opacity:.96}));rimMesh.name='case-rim';rimMesh.position.z=-.08;phone.add(rimMesh);
 const island=new THREE.Mesh(new THREE.ExtrudeGeometry(rrShape(.79,.75,.17),{depth:.07,bevelEnabled:true,bevelSize:.025,bevelThickness:.02,bevelSegments:3}),new THREE.MeshStandardMaterial({color:0x1a1a1c,roughness:.35,metalness:.55}));island.geometry.center();island.position.set(-.5,1.39,-.25);island.rotation.y=Math.PI;phone.add(island);[[-.68,1.55],[-.32,1.47],[-.6,1.2]].forEach(([x,y])=>{const lens=new THREE.Mesh(new THREE.CylinderGeometry(.13,.16,.07,32),new THREE.MeshPhysicalMaterial({color:0x08090d,roughness:.1,metalness:.7,clearcoat:1}));lens.rotation.x=Math.PI/2;lens.position.set(x,y,-.32);phone.add(lens)});phone.rotation.set(viewTarget.x,viewTarget.y,0)}
function updateTexture(force=false){if(!renderer||(!textureDirty&&!force))return;caseTexture.needsUpdate=true;const rim=phone.getObjectByName('case-rim');if(rim)rim.material.color.set(baseColor);textureDirty=false}
function resize3D(){if(!renderer)return;const h=$('#preview-stage'),w=h.clientWidth||600,hh=h.clientHeight||600;renderer.setSize(w,hh,false);camera.aspect=w/hh;camera.updateProjectionMatrix()}
function animate(){raf=requestAnimationFrame(animate);if(!renderer)return;phone.rotation.x+=(viewTarget.x-phone.rotation.x)*.09;phone.rotation.y+=(viewTarget.y-phone.rotation.y)*.09;camera.position.z+=(distance-camera.position.z)*.1;renderer.render(scene,camera)}
$$('[data-view-controls] [data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='front'){viewTarget={x:0,y:0,z:0};distance=7.2}else if(v==='back'){viewTarget={x:0,y:Math.PI,z:0};distance=7.2}else if(v==='angle'){viewTarget={x:.2,y:Math.PI-.55,z:0};distance=7.2}else{viewTarget={x:.18,y:Math.PI-.5,z:0};distance=7.2}});addEventListener('resize',resize3D);
try{const saved=localStorage.getItem(STORE);if(saved)restore(JSON.parse(saved),false);else{snapshot();render();renderLayers()}}catch(e){snapshot();render();renderLayers()}updateActions();init3D();
})();
